[DPE-3086] Improve CI/CD pipeline
canonical/charmed-kafka-rock pull request #17
Opened 2023-12-13 09:10 UTC by deusebio

2023-12-14 17:19 UTC, zmraul approved these changes
LGTM

2023-12-14 17:19 UTC, zmraul commented on .github/workflows/publish.yaml
> +
nit: a couple of extra empty lines

2023-12-14 17:19 UTC, zmraul commented on .github/workflows/publish.yaml
> +          IMAGE_NAME="${REPOSITORY}charmed-kafka"
nit: `REPOSITORY` is not used anywhere else that I see, so it can all be declared here

2024-01-22 15:38 UTC, zmraul requested changes
Same [comment in zookeeper](https://github.com/canonical/charmed-zookeeper-rock/pull/26#pullrequestreview-1836761622) can be squeezed on this PR as well

2024-01-22 15:39 UTC, zmraul approved these changes

2024-01-22 17:40 UTC, marcoppenheimer approved these changes

2024-01-22 20:40 UTC, merged